In [6]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns




In [7]:
#scalar and array inputs
scalar = 3.7
arr = np.array([1, 2, 3, 4, 5,6])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)
# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)

sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
tan: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]
asin: [0.16744808 0.33983691 0.52359878 0.72972766 0.98511078 1.57079633]
acos: [1.40334825 1.23095942 1.04719755 0.84106867 0.58568554 0.        ]
atan: [0.78539816 1.10714872 1.24904577 1.32581766 1.37340077 1.40564765]


In [8]:
# Creating a 2x2 matrix
matrix = np.array([[1, 2], [3, 4],[5,6]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[1 2]
 [3 4]
 [5 6]]

sin:
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155 ]]

cos:
 [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]
 [ 0.28366219  0.96017029]]

tan:
 [[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]
 [-3.38051501 -0.29100619]]

asine:
 [[0.16744808 0.33983691]
 [0.52359878 0.72972766]
 [0.98511078 1.57079633]]

acosine:
 [[1.40334825 1.23095942]
 [1.04719755 0.84106867]
 [0.58568554 0.        ]]

atangent:
 [[0.78539816 1.10714872]
 [1.24904577 1.32581766]
 [1.37340077 1.40564765]]

exp:
 [[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]
 [148.4131591  403.42879349]]

log (natural):
 [[0.         0.69314718]
 [1.09861229 1.38629436]
 [1.60943791 1.79175947]]

abs:
 [[1 2]
 [3 4]
 [5 6]]

sqrt:
 [[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]

rem (remainder when divided by 2):
 [[1 0]
 [1 0]
 [1 0]]

round:
 [[1 2]
 [3 4]
 [5 6]]

floor:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]

ceil:
 [[1. 2

In [18]:
#vector
vec = np.array([[1.2,3.2,8.2],[9.2,5.2 ,6.2]])


# 1. Maximum value and index of max element
max_value = np.max(vec)
max_index = np.argmax(vec)  # Index of max element

# 2. Minimum value and index of min element
min_value = np.min(vec)
min_index = np.argmin(vec)  # Index of min element

# 3. Length of the vector
vec_length = len(vec)  # Equivalent to MATLAB's length()

# 4. Sorting in ascending order
sorted_vec = np.sort(vec)



entire_sorted = -np.sort(-vec.flatten())
# 5. Sum of elements
sum_values = np.sum(vec)

# 6. Product of elements
prod_values = np.prod(vec)

# 7. Median value
median_value = np.median(vec)

# 8. Mean value
mean_value = np.mean(vec)

# 9. Standard deviation
std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("Entire Sorted vector:", entire_sorted)

print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)

Max value: 9.2 at index 3
Min value: 1.2 at index 0
Length of vector: 2
Sorted vector: [[1.2 3.2 8.2]
 [5.2 6.2 9.2]]
Entire Sorted vector: [9.2 8.2 6.2 5.2 3.2 1.2]
Sum of elements: 33.199999999999996
Product of elements: 9339.592703999999
Median value: 5.7
Mean value: 5.533333333333332
Standard deviation: 2.7487370837451066
